version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "123123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goodsapp
    ports:
      - "40140:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=GoodsManagementDb;User=sa;Password=123123;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db
    restart: unless-stopped

volumes:
  sql_data:
