version: '3.4'

services:
  webapp:
    build:
      context: .
      dockerfile: GoodsManagement/Dockerfile
    ports:
      - "40140:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=GoodsManagementDb;User=sa;Password=123123;Encrypt=False;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "123123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
